
#Server and Client side changes.
[common]
	#The amount of armor lava monsters have.
	monsterArmor = 0.0
	#The distance a lava monster will begin attacking. (maximum of 35)
	monsterRange = 17.0
	#Ticks a monster must wait after attacking before it can start winding up again.
	attackCooldown = 80
	#Number of fireballs shot with each attack.
	attackShots = 3
	#Ticks between each fireball shot in an attack.
	attackSpacing = 6
	#Ticks it takes before a monster can start an attack.
	attackWindup = 60
	#If true, lava monsters will not spawn above layer 16.
	depthHazard = false
	#If true, lava monsters do not require a source block to spawn.
	flowingLava = false
	#If true, lava monsters will be able to spawn in lava one block deep.
	shallowLava = false
	#The chance for a lava monster spawn attempt to be successful.
	spawnChance = 0.05
	#The number of ticks between each lava monster spawn attempt.
	spawnFrequency = 10
	#Allows you to choose which dimensions the Lava Monster spawns in. Add dimensions by their registry name/id, and separate them with commas, no spaces.
	dimensionWhitelist = "minecraft:overworld,minecraft:the_nether,good_nights_sleep:nightmare"

